### PR TITLE
Docker automated deployment

### PR DESCRIPTION
**Pull request by javierLiarte**
- Modified gulpfile.js; modified serve task host and port to get values from environment variables; added dev task for running dev sequence; added make-config task to generate js/config.js; added make-config prerequisite to build task;
- Modified index.html to load autogenerated config from js/config.js
- Modified app.js to include app.config dependency
- Modified services/api.js to get mojofyApiUrl config variable and use it in api var, removing harcoded api url dependency
- Modified package.json; added start-local, dev and dev-local scripts; updated start script for docker deployment; added node and npm deps to engines; added gulp, gulp-ng-config and buffer-to-vinyl to dependencies and run-sequence to devDependencies
- Added Dockerfile and .dockerignore to build backend container
- Modified .gitignore to ignore .idea dir and autogenerated config js/config.js
- Updated dist generated files

### CODE REVIEW

**Comment by javierLiarte** [comment]
cambia el script por defecto de npm para arrancar en local (sin docker) usar `npm run-script start-local`

**Review by CodingCarlos — APPROVED** [review]
Super cool! We'll be merging this asap!

**Review by DevStarlight — APPROVED** [review]
since I live deployed everything in OSX, all the necessary changes were made and included in #24

**Comment by DevStarlight** [comment]
I've merged & tested everything and works like a charm!

**Pull request merged**
