### PR TITLE
[156613344] Hot fixed video details.

### PR DESCRIPTION
**Pull request by alvaromart**
video-detail-view.html Added class card-video-detail to section, added padding in css to show more space. Video author, remove title and make value strong. video-detail-show-info, added ng-init showDetails = true.

video-detail-view.css. Added cursor pointer over card-user-info-desktop, navigate to user videos. Added card-video-detail and padding to show more space in card.

Note: Missing last requirement center professional and not user resource. Resource has the same widht and height and it should have to be center aligned with professional field.

### CODE REVIEW

**Review by CodingCarlos — APPROVED** [review]
Good work! Aproved!

**Review by DevStarlight — APPROVED** [review]

**Comment by CodingCarlos** [comment]
Have we merged this without updating changelog, release and package?

**Comment by alvaromart** [comment]
Yes, it was a PR to designHotFixes, not develop. Jesús in designHotFixes will also add these changes in release notes. Maybe i could have managed to make this fix directly to develop and update release note, it would have deliver value to user, sooner, before than designHotFixes finishes.

**Comment by CodingCarlos** [comment]
Oh, dammmmn, didn't seen it. My fault, sorry :fearful:

**Pull request merged**
